version: '3.8'

services:
  postgis:
    container_name: reactive-transactional-postgis
    image: postgis/postgis:15-3.4-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mobility_db
      POSTGRES_USER: rci
      POSTGRES_PASSWORD: rci
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgis_data:/var/lib/postgresql/data
      - ./server/src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./server/src/main/resources/function_notify_event.sql:/docker-entrypoint-initdb.d/02-functions.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rci -d mobility_db"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - mobility-network

  server:
    container_name: reactive-transactional-server
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - BUILD_DATE=${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        - VCS_REF=${VCS_REF:-$(git rev-parse --short HEAD)}
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgis:5432/mobility_db
      - SPRING_DATASOURCE_USERNAME=rci
      - SPRING_DATASOURCE_PASSWORD=rci
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      postgis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - mobility-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=PathPrefix(`/api`)"
      - "traefik.http.services.server.loadbalancer.server.port=8080"

  front:
    container_name: reactive-transactional-front
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - BUILD_DATE=${BUILD_DATE:-$(date -u +'%Y-%m-%dT%H:%M:%SZ')}
        - VCS_REF=${VCS_REF:-$(git rev-parse --short HEAD)}
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - mobility-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=PathPrefix(`/`)"
      - "traefik.http.services.front.loadbalancer.server.port=3000"

volumes:
  postgis_data:
    driver: local

networks:
  mobility-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16


