name: 🐛 Bug Report
description: Report a bug in COP
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! This helps us improve COP for everyone.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I've searched existing issues and this is not a duplicate
          required: true
        - label: I'm using the latest version of COP
          required: true
        - label: This is not a security vulnerability (use security@kriir.com instead)
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe expected behavior...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe actual behavior...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - API (Spring Boot backend)
        - Dashboard (React frontend)
        - ML Engine (Prediction models)
        - Database (PostgreSQL/PostGIS)
        - Docker/Deployment
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: [e.g. Ubuntu 22.04]
        - Browser: [e.g. Chrome 91]
        - COP Version: [e.g. v0.1.0]
        - Docker Version: [e.g. 24.0.0]
        - Java Version: [e.g. OpenJDK 17]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Screenshots
      description: Add any relevant logs or screenshots
      placeholder: Paste logs here or attach screenshots...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem