name: ✨ Feature Request
description: Suggest a new feature for COP
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Help us understand what you'd like to see in COP.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission checklist
      options:
        - label: I've searched existing issues and this is not a duplicate
          required: true
        - label: This feature aligns with COP's ransomware defense mission
          required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - Ransomware Prediction
        - Kill-Chain Monitoring
        - Automated Response
        - Threat Intelligence
        - Dashboard/UI
        - API Enhancement
        - ML/AI Capability
        - Integration
        - Performance
        - Security
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or pain point...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to happen?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: What other approaches have you considered?
      placeholder: Describe any alternative solutions...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Important for security
        - Critical - Blocking ransomware defense
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Implementation Effort
      description: How complex do you think this would be?
      options:
        - Small - Few lines of code
        - Medium - Single component change
        - Large - Multiple components
        - Very Large - Major architecture change
        - Unknown

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe how this feature would be used
      placeholder: |
        As a [security analyst/CISO/etc.]
        I want [feature]
        So that [benefit]

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: How would we know this feature is complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, mockups, or references