spring:
  application:
    name: KRIIR-Platform
  
  # R2DBC configuration for reactive database
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/kriir_db?schema=public
    username: kriir
    password: kriir
    pool:
      enabled: true
      max-size: 20
      initial-size: 10
      max-idle-time: 30m
      
  # Liquibase configuration
  liquibase:
    enabled: false # Disable for now, using manual schema
    
  # Actuator configuration
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus
    endpoint:
      health:
        show-details: always

# Server configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Logging
logging:
  level:
    root: INFO
    com.kriir.platform: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG

# Application specific properties
kriir:
  cors:
    allowed-origins: 
      - "http://localhost:3000"
      - "http://localhost:3001"
    allowed-methods: 
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH
      - OPTIONS
    allowed-headers:
      - "*"
    allow-credentials: true
    
  # Security monitoring configuration
  monitoring:
    incident-check-interval: PT10S # Check for new incidents every 10 seconds
    asset-health-check-interval: PT30S # Check asset health every 30 seconds
    
# SpringDoc OpenAPI 3
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    filter: true
  show-actuator: true

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
      
  r2dbc:
    url: ${DATABASE_URL:r2dbc:postgresql://postgres:5432/kriir_db}
    username: ${DATABASE_USER:kriir}
    password: ${DATABASE_PASSWORD}
    
server:
  port: ${PORT:8080}

logging:
  level:
    root: WARN
    com.kriir.platform: INFO
    
kriir:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://kriir-platform.com}

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
      
logging:
  level:
    root: DEBUG
    com.kriir.platform: TRACE